import { type GetStaticProps } from "next";
import Head from "next/head";
import { FilterCard } from "~/components/FilterCard";
import { JobsList } from "~/components/JobsList";
import { FilterProvider } from "~/contexts/filterContext";
import { generateSSHelper } from "~/server/helpers/ssHelper";

export default function Page() {
  return (
    <>
      <Head>
        <title>Job Listing Example</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-teal-200 to-teal-600">
        <div className="flex h-full w-full flex-col items-center gap-8 py-16">
          <FilterProvider>
            <FilterCard />
            <JobsList />
          </FilterProvider>
        </div>
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const ssg = generateSSHelper();

  await ssg.job.getAll.prefetch();

  return {
    props: {
      trpcState: ssg.dehydrate(),
    },
  };
};
